In [2]:
import numpy as np

In [28]:
arr=np.linspace(-0.5,0.5,num=5)
arr

array([-0.5 , -0.25,  0.  ,  0.25,  0.5 ])

In [29]:
np.sum(arr)

0.0

In [8]:
np.outer(arr,arr)

array([[ 0.25  ,  0.125 , -0.    , -0.125 , -0.25  ],
       [ 0.125 ,  0.0625, -0.    , -0.0625, -0.125 ],
       [-0.    , -0.    ,  0.    ,  0.    ,  0.    ],
       [-0.125 , -0.0625,  0.    ,  0.0625,  0.125 ],
       [-0.25  , -0.125 ,  0.    ,  0.125 ,  0.25  ]])

In [7]:
import numpy as np
def mesh_grid(size):    
    x=np.linspace(-(size//2),(size//2),size)
    y=np.linspace(-(size//2),(size//2),size)
    X=[]
    Y=[]
    for j in y:
        X_row=[]
        Y_row=[]
        for i in x:
            X_row.append(i)
            Y_row.append(j)
        X.append(X_row)
        Y.append(Y_row)
    return np.array(X),np.array(Y)

In [8]:
def gaussian_kernel(size,sigma=1):
    

    x=np.linspace(-(size//2),(size//2),size)
    y=np.linspace(-(size//2),(size//2),size)

    xx,yy=mesh_grid(size)
    kernel=np.exp(-(xx**2+yy**2)/(2*sigma**2))
    return kernel/np.sum(kernel)

gaussian_kernel(5)

array([[0.00296902, 0.01330621, 0.02193823, 0.01330621, 0.00296902],
       [0.01330621, 0.0596343 , 0.09832033, 0.0596343 , 0.01330621],
       [0.02193823, 0.09832033, 0.16210282, 0.09832033, 0.02193823],
       [0.01330621, 0.0596343 , 0.09832033, 0.0596343 , 0.01330621],
       [0.00296902, 0.01330621, 0.02193823, 0.01330621, 0.00296902]])

In [11]:
import plotly.express as px
# size=5
# sigma=1
# x=np.linspace(-(size//2),(size//2),size)
# y=np.linspace(-(size//2),(size//2),size)
# xx,yy=mesh_grid(size)
# kernel=np.exp(-(xx**2+yy**2)/(2*sigma**2))
# kernel=kernel/np.sum(kernel)
fig=px.imshow(gaussian_kernel(5))
fig.show()

In [21]:
import cv2
image=cv2.imread('image.jpg')
px.imshow(image)
# cv2.imshow('image',image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [25]:
image[0][0]

array([191, 193, 204], dtype=uint8)

In [24]:
image[0].shape

(577, 3)

In [32]:
px.imshow(image[0:2,0:2])

In [50]:
kernel=gaussian_kernel(3)
height=image.shape[0]
width=image.shape[1]
channel=image.shape[2]
new=np.zeros((height,width,channel),dtype=np.uint8)
for row in range(1,height-1):
    for col in range(1,width-1):
        # print(image[row-1:row+2,col-1:col+2])
        # print(kernel*image[row-1:row+2,col-1:col+2])
        print(np.sum(kernel*image[row-1:row+2,col-1:col+2],axis=0))
        break
    break
        # new[row][col]=np.sum(kernel*image[row-1:row+2,col-1:col+2])


TypeError: 'axis' is an invalid keyword argument for print()

In [45]:
new.shape

(1280, 577, 3)

In [46]:
px.imshow(new)

In [ ]:
def apply_gaussian(image,filter_size):
    