In [1]:
import numpy as np

## Cross Pattern

In [3]:
def cross(size):
    arr=np.zeros((size,size),dtype=np.uint8)
    arr[size//2,:]=1
    arr[:,size//2]=1
    return arr
cross(5)

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)

## Hollow Square

In [4]:
def hollow_square(size):
    arr=np.zeros((size,size),dtype=np.uint8)
    arr[0,:]=1
    arr[-1,:]=1
    arr[:,0]=1
    arr[:,-1]=1
    return arr
hollow_square(7)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

## Upper triangle Matrix

In [21]:
def mat_sum(size):
    arr=np.full((size,size),fill_value='0',dtype='<U7')
    for i in range(size):
        for j in range(size):
            sum_=i+j
            arr[i,j]=f'({i},{j})'
    return arr
mat_sum(5)

array([['(0,0)', '(0,1)', '(0,2)', '(0,3)', '(0,4)'],
       ['(1,0)', '(1,1)', '(1,2)', '(1,3)', '(1,4)'],
       ['(2,0)', '(2,1)', '(2,2)', '(2,3)', '(2,4)'],
       ['(3,0)', '(3,1)', '(3,2)', '(3,3)', '(3,4)'],
       ['(4,0)', '(4,1)', '(4,2)', '(4,3)', '(4,4)']], dtype='<U7')

In [26]:
def upper_triangle(size):
    arr=np.zeros((size,size),dtype=np.int8)
    for i in range(size):
        for j in range(size):
            if i<=j:
                arr[i,j]=-1
    return arr
upper_triangle(5)

array([[-1, -1, -1, -1, -1],
       [ 0, -1, -1, -1, -1],
       [ 0,  0, -1, -1, -1],
       [ 0,  0,  0, -1, -1],
       [ 0,  0,  0,  0, -1]], dtype=int8)

## Checkboard

In [27]:
def checkboard(size):
    arr=np.zeros((size,size),dtype=np.int8)
    for i in range(size):
        for j in range(size):
            if (i+j)%2!=0:
                arr[i,j]=-1
    return arr
checkboard(5)

array([[ 0, -1,  0, -1,  0],
       [-1,  0, -1,  0, -1],
       [ 0, -1,  0, -1,  0],
       [-1,  0, -1,  0, -1],
       [ 0, -1,  0, -1,  0]], dtype=int8)

## Diagonal Line matrix

In [28]:
def diagonal_line(size):
    arr=np.zeros((size,size))
    for i in range(size):
        for j in range(size):
            if i==j:
                arr[i,j]=-1
    return arr
diagonal_line(5)

array([[-1.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0., -1.]])

In [30]:
def X_line(size):
    arr=np.zeros((size,size))
    for i in range(size):
        for j in range(size):
            if i==j or (i+j)==size-1:
                arr[i,j]=-1
    return arr
X_line(5)

array([[-1.,  0.,  0.,  0., -1.],
       [ 0., -1.,  0., -1.,  0.],
       [ 0.,  0., -1.,  0.,  0.],
       [ 0., -1.,  0., -1.,  0.],
       [-1.,  0.,  0.,  0., -1.]])

In [32]:
def inverted_pyramid(size):
    arr=np.zeros((size,size))
    for i in range(size):
        for j in range(size):
            if (i+j)<=size-1 and j>=i:
                arr[i,j]=-1
    return arr
inverted_pyramid(5)

array([[-1., -1., -1., -1., -1.],
       [ 0., -1., -1., -1.,  0.],
       [ 0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [42]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

def resize_image(image, scale_x, scale_y):
    # Get original dimensions
    original_height, original_width = image.shape[:2]

    # Calculate new dimensions
    new_width = int(original_width * scale_x)
    new_height = int(original_height * scale_y)

    # Create an empty array for the resized image
    resized_image = np.zeros((new_height, new_width, image.shape[2]), dtype=image.dtype)

    # Scale factor for coordinate mapping
    for i in range(new_height):
        for j in range(new_width):
            # Calculate original coordinates
            orig_x = int(j / scale_x)
            orig_y = int(i / scale_y)

            # Check bounds
            orig_x = min(orig_x, original_width - 1)
            orig_y = min(orig_y, original_height - 1)

            # Assign pixel value
            resized_image[i, j] = image[orig_y, orig_x]

    return resized_image

# Load an image using OpenCV
image_path = 'C:/Users/Windows/Desktop/hello/Play_Numy_vs_Python/level_1/image.jpg'  # Replace with your image path
image = cv2.imread(image_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Convert BGR to RGB

# Set scale factors
scale_x = 0.1  # Resize width to 50%
scale_y = 0.1  # Resize height to 50%

# Resize the image
resized_image_ = resize_image(image, scale_x, scale_y)

# # Plot the original and resized images
# plt.figure(figsize=(10, 5))
# plt.subplot(1, 2, 1)
# plt.title('Original Image')
# plt.imshow(image)
# plt.axis('off')

# plt.subplot(1, 2, 2)
# plt.title('Resized Image')
# plt.imshow(resized_image)
# plt.axis('off')

# plt.show()
import plotly.express as px
print(image.shape)
print(resized_image_.shape)
px.imshow(resized_image_)



(1280, 577, 3)
(128, 57, 3)
